services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: anjan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: claim-based-authorization
    volumes:
      - claim-based-authorization-data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    restart: always

  admin:
    image: adminer
    restart: always
    ports:
      - 9999:8080

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

volumes:
  claim-based-authorization-data:
    driver: local
